---
# Repository and Path Variables
app_repo: "https://github.com/pravinmishraaws/theepicbook"
app_dest: "/var/www/epicbook"

# User and Permissions
app_user: "www-data"
app_group: "www-data"

nginx_site_name: "epicbook"
app_port: 3000
db_user: "epicbook_user"
db_name: "bookstore"
pm2_home: "/var/www/.pm2"
